### PR TITLE
Revert temporary Dask pinning in CI

### PR DESCRIPTION
**Pull request by jrbourbeau**
With `dask=2021.3.1` out we can remove the temporary version pinning in CI to workaround https://github.com/xgcm/xhistogram/issues/27. Additionally, this PR also switches to installing packages from `conda-forge` instead of `defaults`

### CODE REVIEW

**Comment by jrbourbeau** [comment]
The latest Dask release (`2021.3.1`) dropped support for Python 3.6. This means that all of `xhistogram`s dependencies have now no longer support Python 3.6 so we should probably support as well. I've opened up a PR over in https://github.com/xgcm/xhistogram/pull/40 to do this.

**Review by dougiesquire — APPROVED** [review]
Looks good to me. Thanks for doing this @jrbourbeau

**Comment by dougiesquire** [comment]
Actually, it looks as though some tests are still failing with the old error:

```
        if reduce(mul, shape, 1) != x.size:
>           raise ValueError("total size of new array must be unchanged")
E           ValueError: total size of new array must be unchanged

/usr/share/miniconda3/envs/xhistogram_test_env/lib/python3.6/site-packages/dask/array/reshape.py:206: ValueError
```

**Comment by jrbourbeau** [comment]
Those are due to Dask dropping support for Python 3.6 in `2021.03.1`, which the Python 3.6 builds can't install the release which contains the fix for `ValueError: total size of new array must be unchanged`. Let's hold off on merging this PR until we've dropped Python 3.6 (xref https://github.com/xgcm/xhistogram/pull/40), which should resole the issue altogether

**Comment by dougiesquire** [comment]
Thanks for this @jrbourbeau, merging now

**Comment by jrbourbeau** [comment]
Thanks @dougiesquire!

**Pull request merged**
