### PR TITLE
Example with real world data

### PR DESCRIPTION
**Pull request by dhruvbalwada**
Added onto the tutorial notebook, but adding an example that uses xhistogram to do a volume census.

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks a lot for this @dhruvbalwada! But you have include 7 junk files in your PR: https://github.com/xgcm/xhistogram/pull/3/files

Could you remove them all and just keep `tutorial.ipynb`?

**Comment by rabernat** [comment]
Another thought: maybe we can pull the data from opendap so we don't have to include an actual file. I found and opendap version of WOA13 here:

http://apdrc.soest.hawaii.edu/dods/public_data/WOA/WOA13/1_deg/annual

You want to run "clear all cells" before adding the notebook. It will get run automatically during the documentation build process.

**Comment by willirath** [comment]
Could think about keeping the data file: <https://github.com/xgcm/xhistogram/pull/3/files#diff-8b0dc875488c02c4f095e758ba44ac82>

But 5MB's quite heavy.  What about reducing the size by thinning this
```
<xarray.Dataset>
Dimensions:  (depth: 102, lat: 36, lon: 72)
Coordinates:
  * depth    (depth) float32 0.0 5.0 10.0 15.0 ... 5200.0 5300.0 5400.0 5500.0
  * lat      (lat) float32 -87.5 -82.5 -77.5 -72.5 -67.5 ... 72.5 77.5 82.5 87.5
  * lon      (lon) float32 -177.5 -172.5 -167.5 -162.5 ... 167.5 172.5 177.5
Data variables:
    SA       (depth, lat, lon) float64 ...
    CT       (depth, lat, lon) float64 ...
    O2       (depth, lat, lon) float32 ...
    dz       (depth) float32 ...
```
to `Ocean_TS.isel(depth=slice(0, None, 10), lat=slice(0, None, 2), lon=slice(0, None, 2))`.

Should get you down to <150kB.

**Comment by dhruvbalwada** [comment]
Thanks for the comments guys. 

I decided to take the path that Ryan suggested and directly pull the data from the Opendap server, completely getting rid of the need for saving any data. Worked beautifully when I tried it on the pangeo cloud. :) 

I am new to making pull requests, so not sure if I need to redo the pull request or if the changes I made since your comments will automatically be available. I think they should be automatically available, if not let me know how to proceed.

**Comment by willirath** [comment]
> I am new to making pull requests, so not sure if I need to redo the pull request or if the changes I made since your comments will automatically be available. I think they should be automatically available, if not let me know how to proceed.

A PR always represents the state of the branch in question.  To change, just push more changes to the branch.  So you did it right. :)

**Comment by dhruvbalwada** [comment]
Could also fix #2 and other mentions of options that go with numpy hist to this PR.

**Pull request merged**
